<?php

/**
 * OutingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OutingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OutingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Outing');
    }
}