# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: home, action: index }

trip_details:
  url: /trip
  param: { module: trip, action: index }

trip_add:
  url: /trip/add
  param: { module: trip, action: add }

trip_add_ajax:
  url: /trip/addByAjax
  param: { module: trip, action: addByAjax }

trip_delete:
  url: /trip/delete
  param: { module: trip, action: delete }

trip_delete_all_by_ajax:
  url: /trip/delete_all
  param: { module: trip, action: deleteAllByAjax }

list_trips:
  url: /trips
  param: { module: trip, action: list }

stats:
  url: /stats
  param: { module: stats, action: index }

earnings:
  url: /stats/earnings
  param: { module: stats, action: getEarnings }

mileage:
  url: /stats/mileage
  param: { module: stats, action: getMileage }

settings:
  url: /settings
  param: { module: setting, action: index }

settings_trips:
  url: /settings/trips
  param: { module: setting, action: trips }

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

settings_password:
  url: /settings/password
  param: { module: setting, action: security }
