<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('outing', 'earnings', 'double', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('outing', 'earnings');
    }
}