<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/10/09 15:52:02

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=127.0.0.1;dbname=taxitrackpro',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
