# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: home, action: index }

complete:
  url: /complete
  param: { module: trip, action: complete }

start:
  url: /start
  param: { module: trip, action: start }

stop:
  url: /stop
  param: { module: trip, action: stop }
