# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css,bootstrap.css,http://code.jquery.com/mobile/1.0b2/jquery.mobile-1.0b2.min.css]

  javascripts:    [http://code.jquery.com/jquery-1.6.2.min.js,http://code.jquery.com/mobile/1.0b2/jquery.mobile-1.0b2.min.js,script]

  has_layout:     true
  layout:         layout
